name: Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug GitHub context
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::897722709473:role/github-actions-deployment-role
          aws-region: us-east-1

      - name: Test AWS authentication
        run: aws sts get-caller-identity

      - name: Test SSM connection
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids i-054dc321b27633562 \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["whoami"]' \
            --query "Command.CommandId" \
            --output text)

          echo "Command ID: $COMMAND_ID"

          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id i-054dc321b27633562

          aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id i-054dc321b27633562 \
            --query "StandardOutputContent" \
            --output text
            
      - name: Check Docker on EC2
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids i-054dc321b27633562 \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["docker --version"]' \
            --query "Command.CommandId" \
            --output text)

          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id i-054dc321b27633562

          aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id i-054dc321b27633562 \
            --query "StandardOutputContent" \
            --output text